#!/bin/bash

#SBATCH --time=01:00:00   # walltime
#SBATCH --ntasks=10   # number of processor cores (i.e. tasks)
#SBATCH --mem-per-cpu=1024M   # memory per CPU core
#SBATCH -J "test"   # job name
#SBATCH --mail-user=atsoderquist@gmail.com   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --qos=standby

# Compatibility variables for PBS. Delete if not needed.
export PBS_NODEFILE=`/fslapps/fslutils/generate_pbs_nodefile`
export PBS_JOBID=$SLURM_JOB_ID
export PBS_O_WORKDIR="$SLURM_SUBMIT_DIR"
export PBS_QUEUE=batch

# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE


module load python/3/5

pip install --user joblib
pip install --user keras
pip install --user --upgrade --no-deps git+git://github.com/Theano/Theano.git
pip install --user Pillow
pip install --user h5py

python image_labels.py -i images -r ${HOME}/compute/deep-learning-models/result.csv -l ${HOME}/compute/deep-learning-models/labels.csv
python cluster_data.py -d ${HOME}/compute/deep-learning-models/result.csv -l ${HOME}/compute/deep-learning-models/labels.csv -r ${HOME}/compute/deep-learning-models/dendrogram.csv

exit 0